file = open("sample.txt", "r")
line = file.readline()
print(line)
line2 = file.readline()
print(line2)
line3 = file.readline()
print(line3)
line4 = file.readline()
print(line4)
file.close()

# with open("sample.txt", "r") as file:
#     line = file.readline()
#     print(line)
#     line2 = file.readline()
#     print(line2)
#     line3 = file.readline()
#     print(line3)
#     line4 = file.readline()
#     print(line4)